# Generated by Django 3.2.4 on 2022-03-14 02:35
# replace on server test2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=250, unique=True)),
                (
                    "company_short_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primary_ISIN",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "primary_ticker",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("website_link", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=25, unique=True)),
                ("description", models.CharField(max_length=250)),
                ("website_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GHGQuant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=25, null=True)),
                ("reporting_year", models.PositiveIntegerField()),
                (
                    "ghg_scope_1",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_loc_scope_2",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_mkt_scope_2",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_purch_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_capital_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_fuel_energy_loc_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_fuel_energy_mkt_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_upstream_td_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_wate_ops_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_bus_travel_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_commute_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_up_leased_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_downstream_td_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_proc_sold_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_use_sold_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_eol_sold_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_down_leased_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_franchises_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_investments_scope3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "ghg_other",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "purch_ghg_offsets",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="input.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="input.source",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GHG Quantitative",
                "ordering": ["update_date"],
            },
        ),
    ]
