# Generated by Django 2.2.12 on 2022-02-21 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghgquant',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ghgquant',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to=settings.AUTH_USER_MODEL),
        ),
    ]
