from django.contrib import admin

admin.autodiscover()
admin.site.enable_nav_sidebar = False

from corporates.models.netzero import NetZero

from .models import (
    Corporate,
    CorporateGrouping,
    # Country,
    # Industry_1,
    # Industry_2,
    # Activity,
    GeneralInfo,
    GICS,
    Benchmark,
    ISIN,
    FinnhubMatching,
    Tradingview,
    Ticker,
    Site,
    MSCI,
    SBTI,
    Matching,
    Library,
    TargetQuant,
    GHGMetrics,
    TargetQuant,
    Investment,
    CDP,
    GHGQuant,
    Verification,
    Score,
    CompanyScore,
    LatestCompanyScore,
    Source,
    UserProfile,
    NetZero,
    CO2Pricing,
    StockData,
    Stats,
    CalcMetrics,
)


classes_to_register = [
    Corporate,
    CorporateGrouping,
    # Country,
    # Industry_1,
    # Industry_2,
    # Activity,
    GeneralInfo,
    GICS,
    Benchmark,
    ISIN,
    Tradingview,
    Ticker,
    Site,
    MSCI,
    SBTI,
    Matching,
    Library,
    TargetQuant,
    GHGMetrics,
    Investment,
    CDP,
    GHGQuant,
    Verification,
    Score,
    CompanyScore,
    LatestCompanyScore,
    Source,
    UserProfile,
    NetZero,
    CO2Pricing,
    FinnhubMatching,
    StockData,
    Stats,
    CalcMetrics,
]

for class_to_register in classes_to_register:
    admin.site.register(class_to_register)
