from django.urls import path
from . import views

urlpatterns = [
    path("<str:corp_name>/", views.corporates_search, name="corporates_search"),
    path("", views.corporates_home, name="corporates_home"),
    path(
        "charts/html_exports/<str:folder_name>/<str:file_name>",
        views.show_html,
        name="html_exports",
    ),
    path("input/home/", views.ChooseCorporateList.as_view(), name="input_home"),
    path(
        "input/<str:corp_name>/general/",
        views.InputGeneral.as_view(),
        name="input_by_corp_general",
    ),
    path(
        "input/<str:corp_name>/ghg/home/",
        views.GHGListView.as_view(),
        name="input_by_corp_ghg_home",
    ),
    path(
        "input/<str:corp_name>/ghg/create/",
        views.GHGListCreate.as_view(),
        name="input_by_corp_ghg_create",
    ),
    path(
        "input/<str:corp_name>/ghg/<int:pk>/",
        views.GHGListUpdate.as_view(),
        name="input_by_corp_ghg_update",
    ),
    path(
        "input/<str:corp_name>/ghg/delete/<int:pk>/",
        views.GHGListDelete.as_view(),
        name="input_by_corp_ghg_delete",
    ),
    path(
        "input/<str:corp_name>/verif/home",
        views.VerifListView.as_view(),
        name="input_by_corp_verif_home",
    ),
    path(
        "input/<str:corp_name>/verif/create/",
        views.VerifListCreate.as_view(),
        name="input_by_corp_verif_create",
    ),
    path(
        "input/<str:corp_name>/verif/<int:pk>/",
        views.VerifListUpdate.as_view(),
        name="input_by_corp_verif_update",
    ),
    path(
        "input/<str:corp_name>/verif/delete/<int:pk>/",
        views.VerifListDelete.as_view(),
        name="input_by_corp_verif_delete",
    ),
    path(
        "input/<str:corp_name>/target/home",
        views.TargetListView.as_view(),
        name="input_by_corp_target_home",
    ),
    path(
        "input/<str:corp_name>/target/create/",
        views.TargetListCreate.as_view(),
        name="input_by_corp_target_create",
    ),
    path(
        "input/<str:corp_name>/target/<int:pk>/",
        views.TargetListUpdate.as_view(),
        name="input_by_corp_target_update",
    ),
    path(
        "input/<str:corp_name>/target/delete/<int:pk>/",
        views.TargetListDelete.as_view(),
        name="input_by_corp_target_delete",
    ),
    path(
        "input/<str:corp_name>/cdp/home",
        views.CDPListView.as_view(),
        name="input_by_corp_cdp_home",
    ),
    path(
        "input/<str:corp_name>/cdp/create/",
        views.CDPListCreate.as_view(),
        name="input_by_corp_cdp_create",
    ),
    path(
        "input/<str:corp_name>/cdp/<int:pk>/",
        views.CDPListUpdate.as_view(),
        name="input_by_corp_cdp_update",
    ),
    path(
        "input/<str:corp_name>/cdp/delete/<int:pk>/",
        views.CDPListDelete.as_view(),
        name="input_by_corp_cdp_delete",
    ),
    path(
        "input/<str:corp_name>/netzero/home",
        views.NetZeroListView.as_view(),
        name="input_by_corp_netzero_home",
    ),
    path(
        "input/<str:corp_name>/netzero/create/",
        views.NetZeroListCreate.as_view(),
        name="input_by_corp_netzero_create",
    ),
    path(
        "input/<str:corp_name>/netzero/<int:pk>/",
        views.NetZeroListUpdate.as_view(),
        name="input_by_corp_netzero_update",
    ),
    path(
        "input/<str:corp_name>/netzero/delete/<int:pk>/",
        views.NetZeroListDelete.as_view(),
        name="input_by_corp_netzero_delete",
    ),
    path(
        "input/<str:corp_name>/generalinfo/home",
        views.GeneralInfoListView.as_view(),
        name="input_by_corp_generalinfo_home",
    ),
    path(
        "input/<str:corp_name>/generalinfo/create/",
        views.GeneralInfoListCreate.as_view(),
        name="input_by_corp_generalinfo_create",
    ),
    path(
        "input/<str:corp_name>/generalinfo/<int:pk>/",
        views.GeneralInfoListUpdate.as_view(),
        name="input_by_corp_generalinfo_update",
    ),
    path(
        "input/<str:corp_name>/generalinfo/delete/<int:pk>/",
        views.GeneralInfoListDelete.as_view(),
        name="input_by_corp_generalinfo_delete",
    ),
]
