# Generated by Django 2.2.12 on 2022-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('filename', models.CharField(default='dummy', max_length=20)),
            ],
        ),
    ]
