# Generated by Django 3.2.4 on 2022-07-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghgquant',
            name='cdp_override',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does this GHG Inventory override GHG Inventory reported to CDP'),
        ),
    ]
