# Generated by Django 3.2.4 on 2022-07-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyscore',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corporates.scoreversion'),
        ),
        migrations.AddField(
            model_name='latestcompanyscore',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corporates.scoreversion'),
        ),
    ]
