# Generated by Django 2.2.12 on 2021-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='filename',
            field=models.CharField(default='dummy', max_length=20),
        ),
    ]
