# Generated by Django 3.2.4 on 2022-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestcompanyscore',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
