# Generated by Django 3.2.4 on 2022-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0002_ghgquant_cdp_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetquant',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('underway', 'Underway'), ('achieved', 'Achieved'), ('expired', 'Expired'), ('revised', 'Revised'), ('replaced', 'Replaced'), ('retired', 'Retired')], default='underway', max_length=100, null=True),
        ),
    ]
