# Generated by Django 3.2.4 on 2022-06-22 10:27

import corporates.models.general
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0002_auto_20220621_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='upload',
            new_name='upload_1',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='upload_2',
            field=models.FileField(blank=True, null=True, upload_to=corporates.models.general.user_directory_path),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='upload_3',
            field=models.FileField(blank=True, null=True, upload_to=corporates.models.general.user_directory_path),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='upload_4',
            field=models.FileField(blank=True, null=True, upload_to=corporates.models.general.user_directory_path),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='upload_5',
            field=models.FileField(blank=True, null=True, upload_to=corporates.models.general.user_directory_path),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='corporates.corporate'),
        ),
    ]
