# Generated by Django 3.2.4 on 2022-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0002_alter_latestcompanyscore_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestcompanyscore',
            name='score_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
