# Generated by Django 2.2.12 on 2021-07-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0002_corporate_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
