# Generated by Django 3.2.4 on 2022-04-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0003_latestcompanyscore_score_pct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporategrouping',
            old_name='company_id',
            new_name='company',
        ),
    ]
