# Generated by Django 3.2.4 on 2022-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0003_targetquant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetquant',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('underway', 'Underway'), ('achieved', 'Achieved'), ('expired', 'Expired'), ('revised', 'Revised'), ('replaced', 'Replaced'), ('retired', 'Retired')], default='underway', max_length=100, null=True),
        ),
    ]
