# Generated by Django 3.2.4 on 2022-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0004_auto_20220625_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghgquant',
            old_name='ghg_other',
            new_name='ghg_other_downstream',
        ),
        migrations.AddField(
            model_name='ghgquant',
            name='ghg_other_upstream',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
