# Generated by Django 3.2.4 on 2022-06-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0005_auto_20220626_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghgquant',
            old_name='ghg_other_downstream',
            new_name='ghg_other_downstream_scope3',
        ),
        migrations.RenameField(
            model_name='ghgquant',
            old_name='ghg_other_upstream',
            new_name='ghg_other_upstream_scope3',
        ),
    ]
