# Generated by Django 3.2.4 on 2022-07-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0007_auto_20220703_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='netzero',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
