# Generated by Django 3.2.4 on 2022-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0008_netzero_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp',
            name='score',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('a-', 'A-'), ('b', 'B'), ('b-', 'B-'), ('c', 'C'), ('c-', 'C-'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('not_scored', 'Not Scored'), ('not_available', 'Not Available')], default='f', max_length=25, null=True, verbose_name='CDP Score'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='document',
            field=models.CharField(choices=[('sustainability_report', 'Sustainability Report'), ('tcfd_report', 'TCFD Report'), ('progress_report', 'Progress Report')], default='sustainability_report', max_length=100, null=True, verbose_name='Type of Documents'),
        ),
    ]
