# Generated by Django 3.2.4 on 2022-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0009_auto_20220704_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='document',
            field=models.CharField(choices=[('sustainability_report', 'Sustainability Report'), ('tcfd_report', 'TCFD Report'), ('progress_report', 'Progress Report'), ('climate_plan', 'Climate Plan')], default='sustainability_report', max_length=100, null=True, verbose_name='Type of Documents'),
        ),
        migrations.AlterField(
            model_name='ghgquant',
            name='source',
            field=models.CharField(blank=True, choices=[('public', 'Public source'), ('cdp_2021', '2021 CDP Climate Change Questionnaire'), ('cdp_2020', '2020 CDP Climate Change Questionnaire'), ('final', 'Final')], default='public', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='targetquant',
            name='source',
            field=models.CharField(choices=[('public', 'Public source'), ('cdp_2020', 'CDP Climate Change Questionnaire'), ('sbti', 'Science-Based Target Institute (SBTi)')], default='public', max_length=20),
        ),
    ]
